# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSInstanceDJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='OSMasterDJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logfilename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchedby', models.CharField(max_length=100)),
                ('searchdate', models.DateField()),
                ('OSInstances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.OSInstanceDJ')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seacrhlog', models.CharField(max_length=1000)),
                ('OSInstances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.OSInstanceDJ')),
                ('searchedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.SearchID')),
            ],
        ),
        migrations.CreateModel(
            name='SearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='osinstancedj',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.OSMasterDJ'),
        ),
    ]
