# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osinstancedj',
            name='sshport',
            field=models.IntegerField(default=22),
        ),
    ]
