# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160828_0445'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.OSMasterDJ')),
                ('searchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.SearchID')),
            ],
        ),
        migrations.RemoveField(
            model_name='searchlogs',
            name='OSInstances',
        ),
        migrations.RemoveField(
            model_name='searchlogs',
            name='searchedid',
        ),
        migrations.AddField(
            model_name='searchlogs',
            name='resultserver',
            field=models.ForeignKey(default='dcim', on_delete=django.db.models.deletion.CASCADE, to='app1.ResultServer'),
        ),
    ]
