# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20160828_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlogs',
            name='resultserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ResultServer'),
        ),
    ]
