# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20160828_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultserver',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
