# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_resultserver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlogs',
            name='resultserver',
        ),
        migrations.DeleteModel(
            name='SearchLogs',
        ),
    ]
