# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_searchlogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResultServer',
            new_name='ResultServer1',
        ),
        migrations.RenameModel(
            old_name='SearchLogs',
            new_name='SearchLogs1',
        ),
    ]
