# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20160828_0653'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resultserver1',
            table='app1_resultserver1',
        ),
    ]
