# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20160828_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultserver1',
            options={'managed': True},
        ),
    ]
