# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20160828_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultserver1',
            old_name='name',
            new_name='sname',
        ),
    ]
