# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20160828_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seacrhlog', models.CharField(max_length=2000)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
