# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20160828_0802'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='resultserver',
            table='app1_resultserver1',
        ),
    ]
