# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20160828_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultserver',
            options={},
        ),
        migrations.AlterModelTable(
            name='searchlogs',
            table=None,
        ),
    ]
