# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20160828_0808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultserver',
            old_name='sname',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='resultserver',
            table=None,
        ),
    ]
