# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_auto_20160828_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchlogs',
            options={'managed': False},
        ),
    ]
