# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_auto_20160828_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogs2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logline', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='searchlogs1',
            old_name='seacrhlog',
            new_name='logs',
        ),
        migrations.RemoveField(
            model_name='searchlogs1',
            name='rserver',
        ),
    ]
