# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20160828_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogs3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logline', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchLogs',
        ),
        migrations.DeleteModel(
            name='SearchLogs1',
        ),
        migrations.DeleteModel(
            name='SearchLogs2',
        ),
    ]
