# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20160828_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchLogs3',
        ),
    ]
