# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_delete_searchlogs3'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLogs4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logline', models.CharField(max_length=2000)),
                ('rserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ResultServer')),
            ],
        ),
    ]
