# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_remove_resultserver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchid',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='searchid',
            name='searchdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
