# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_auto_20160828_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultserver',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
