# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-14 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_resultserver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultserver',
            name='ip',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
