# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-28 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_osinstancedj_sshport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchid',
            name='OSInstances',
        ),
        migrations.AlterField(
            model_name='searchlogs',
            name='seacrhlog',
            field=models.CharField(max_length=2000),
        ),
    ]
